name: CI
on:
  workflow_call:
    secrets:
      MDS_USERNAME:
        required: true
      MDS_PASSWORD:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      memcached:
        image: memcached:1.4.31
        ports:
          - 11211/udp
    env:
      MEMCACHE_SERVERS: "localhost:11211"
      MDS_USERNAME: ${{ secrets.MDS_USERNAME }}
      MDS_PASSWORD: ${{ secrets.MDS_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby 3.1.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          gem install bundler:2.5.6
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: (Lint and) Test
        env:
          MEMCACHE_SERVERS: "localhost:11211"
        run: |
          # bundle exec rubocop
          bundle exec rspec
          echo $?
